Feature/editor assignment
InTouch-Val/INtouch pull request #217
Opened 2024-05-19 18:31 UTC by sashadudkina5

редактор текста в ЛК клиента в выполнении домашки

2024-05-20 08:16 UTC, JackSheepe commented
Оставил комментарии в кайтене

2024-05-21 07:22 UTC, JackSheepe commented
Сломался размер почему то во время создания домашки
![image](https://github.com/InTouch-Val/INtouch/assets/113531456/95486557-251d-4421-b0ff-27defbbf93a2)
Стили не сохраняются, потому что отправляется просто текст, нужно чтобы отправлялся контент как в AddAssignment.jsx updateBlock (383строка) там есть функция getObjectFromEditorState вот ей нужно воспользоваться и в completeAssignmentsjsx updateBlock newReply, этот reply потом нужно будет декодировать когда получаешь его с сервера с помощью initializeEditorWithText в editor-toolbar там есть else if (block.reply) его скорей всего придется декодировать так же как и если block.description = true

2024-06-02 08:59 UTC, JackSheepe reviewed
Так же судя по всему валидация ClientAssignmentBlock ломает превью во время того когда психолог нажимает на глазик при создании домашки.
Но редактор работает как надо это хорошо, молодец 😊👍

2024-06-02 08:59 UTC, JackSheepe commented on frontend/src/service/ClientAssignmentBlocks.tsx
> -            }}
Это нужно для режима просмотра в создании домашки,
Так же нужно запретить вводить текст если isView = true, это нужно для того чтобы когда психолог смотрит выполненую домашку он не мог вводить и изменять там ответы

2024-06-02 08:59 UTC, JackSheepe commented on frontend/src/service/psyAssignment/Block/Block.tsx
> +          >
isValid не инициализирован и не передан в этот компононент, это вызывает ошибку когда психолог пытается редактировать опубликованную домашку

2024-06-02 08:59 UTC, JackSheepe commented on frontend/src/service/editors-toolbar.tsx
> +    }, [isMobileWidth]); // Пустой массив зависимостей означает, что эффект будет вызван только при монтировании компонента
Не совсем понимаю зачем снова вставлять изначальный текст при изменении ширины окна, так же 100 миллисекунд может не хватить если блоков много

2024-06-05 16:20 UTC, yuferevaleksey requested changes

2024-06-05 16:20 UTC, yuferevaleksey commented on frontend/src/components/client/CompleteAssignments/CompleteAssignments.tsx
> +    console.log("blocks", blockInfo);
Забыла логи

2024-06-05 16:20 UTC, yuferevaleksey commented on frontend/src/components/client/DiaryPage/DiaryPageClient.tsx
> +  console.log(diary)
забыла лог

2024-06-05 16:20 UTC, yuferevaleksey commented on frontend/src/components/client/MyDiary/CardDiary/CardDiary.tsx
> +  const parseText = () => {
Нет возвращамого типа

2024-06-05 16:20 UTC, yuferevaleksey commented on frontend/src/components/client/MyDiary/CardDiary/CardDiary.tsx
> +  const parseText = () => {
parseText- неподходящее имя для функции. parseEventDetailsText 
Я когда читаю код, долджен понять что делает функция не заглядывая в нее.

2024-06-05 16:20 UTC, yuferevaleksey commented on frontend/src/service/ClientAssignmentBlocks.tsx
> +          ? JSON.parse(block.content)
try catch ?

2024-06-05 16:20 UTC, yuferevaleksey commented on frontend/src/utils/helperFunction/getBlockConfig.ts
> +export const getBlockConfig = (getValues: (fieldName: string) => any, fieldName: string) => ({
any?

2024-06-05 16:20 UTC, yuferevaleksey commented on frontend/vite.config.ts.timestamp-1717240154928-60c56adc0e75b.mjs
> +// vite.config.ts
Что это за файл ?

2024-06-10 10:47 UTC, sashadudkina5 commented on frontend/src/utils/helperFunction/getBlockConfig.ts
> +export const getBlockConfig = (getValues: (fieldName: string) => any, fieldName: string) => ({
поставила временно чтобы не задерживаться  и забыла потом вернуться поправить

2024-06-10 10:48 UTC, sashadudkina5 commented on frontend/vite.config.ts.timestamp-1717240154928-60c56adc0e75b.mjs
> +// vite.config.ts
мне кажется я его случайно создала, но сама не заметила как 🥲
удалю

2024-06-18 13:39 UTC, JackSheepe approved these changes
Всё работает отлично молодец 😊👌

_Там много в консоли ошибок когда в дневниках, и когда при просмотре сделаной домашки психологом нажимаешь на стрелочку всплывает попап что вы не сохранили изменения этого не должно быть. Это наверное лучше вынести в отдельные задачи а эту уже закрыть, она же работает ))_

_Хотя пока ждёшь апрува Алексея посмотри может там можно исправить быстренько_

2024-06-21 19:37 UTC, yuferevaleksey approved these changes

2024-06-21 19:43 UTC, merged