fix: text in assignments should validate Immediately
InTouch-Val/INtouch pull request #219
Opened 2024-05-20 10:32 UTC by JackSheepe

Исправлен баг с тем что писался текст ошибки даже при том что ошибки не было,
Так же исправлен баг когда текст ошибки в блоке текст не удалялся даже при том что ошибки уже не было,
При редактировании текст который был вставлен из драфта сразу же валидируется чтобы не дать пользователю опубликовать задачу с ошибками
https://int.kaiten.ru/space/287767/card/32820551?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImNvbXBhcmlzb24iOiJlcSIsImtleSI6Im1lbWJlciIsInZhbHVlIjo1NzAzMTV9XX1dfQ

2024-05-22 09:55 UTC, sashadudkina5 commented
В файле ClientAssignmentBlocks.tsx есть константа const maxInputLength = 1000;
Вижу, что в твоем пулреквесте тоже используется 1000

например
maxLength === 1000

Есть предложение вынести в глобальные константы эту тыщу (в файл constants.ts в utils) и использовать ее оттуда

2024-06-05 16:04 UTC, yuferevaleksey requested changes

2024-06-05 16:04 UTC, yuferevaleksey commented on frontend/src/service/editors-toolbar.tsx
> +        maxLength === 1000
Согласен, числа лучше пернести в константу и держать в одном месте, 1000, 200, 20
порпавь и в других местах. 

Почему важно- вдруг Валя скажет изменить правила валидации - не 1000 а 600 строк. В случае константы меняется одно есто и все. 

В случае множества мест и поиск по проекту черевато что исправишь другую цифру которыя отвечает за другое.

2024-06-10 19:08 UTC, sashadudkina5 approved these changes

2024-06-18 13:47 UTC, merged