refactor assignment page
InTouch-Val/INtouch pull request #226
Opened 2024-05-21 19:26 UTC by RinVeber

-- рефакторинг страницы домашек
-- перевел всю логику с запросами через редакс
-- добавил библиотеку с хуком useInView взамен useObserve
-- сделал HOC для табов
-- связал пагинацию со стором

2024-05-26 08:10 UTC, yuferevaleksey commented on frontend/src/routes/AssignmentsPageRefactor/AssignmentsPage.tsx
> +}) {
Нужно указать тип для входных и выходных параметров

2024-05-26 08:10 UTC, yuferevaleksey commented on frontend/src/routes/AssignmentsPageRefactor/AssignmentsPage.tsx
> +  const handleDeleteClick = (assignmentId) => {
Входной и выходной тип должны быть указаны

2024-05-26 08:10 UTC, yuferevaleksey commented on frontend/src/routes/AssignmentsPageRefactor/AssignmentsPage.tsx
> +                setSearchTerm(e.target.value);
Я думаю будеть разумным перенести это в отдельную функцию

2024-05-26 08:10 UTC, yuferevaleksey commented on frontend/src/routes/AssignmentsPageRefactor/FilterDropDown/FilterDropDown.tsx
> +      case "add_date": {
Сделать ENUM - SomeEnum.AddDate

2024-05-26 08:10 UTC, yuferevaleksey commented on frontend/src/routes/AssignmentsPageRefactor/FilterDropDown/FilterDropDown.tsx
> +      case "add_date": {
Так же я указывал в задаче что направление сортировки должно быть сделанно одним полем DESC, ASC.
И передавать поле которое нудно отсортировать отдельным параметром. Нужноо синхронизироваться с Бэком для доработок

2024-05-26 08:10 UTC, yuferevaleksey commented on frontend/src/routes/AssignmentsPageRefactor/TabsAssignments/Hoc.tsx
> +    console.log(assignments)
Лишний

2024-05-26 08:10 UTC, yuferevaleksey commented on frontend/src/store/entities/assignments/assingmentsApi.ts
> +          /\s+/g,
Напиши плиз что делает регулярка в комментарии выше.

2024-05-26 08:10 UTC, yuferevaleksey commented on frontend/src/store/slices/assignments/assignmentSlice.ts
> +  activeLanguage: "all" | "en" | "es" | "fr" | "de" | "it";
Enum это должен быть

2024-05-26 08:10 UTC, yuferevaleksey commented on frontend/src/store/slices/assignments/assignmentSlice.ts
>    activeTab: "library" | "favorites" | "my-list";
Тоже

2024-05-26 08:18 UTC, yuferevaleksey requested changes

2024-05-26 08:18 UTC, yuferevaleksey commented on frontend/src/components/psy/AssignmentTile.tsx
>  const formatDate = (dateString) => {
В целом ты молодец, хорошо переделал. 
Общие замечания: 
1) "some-value-1" | "some-value-2" должны иметь enum тип
2) Все функции должны иметь тип возращеного значения. Если функция ничего не возвращает - void
3) Все функции должны иметь тип принимаемых значений
4) Нужно избавляться от использования сравнения со строками. Теперь все делается либо через константу, или enum. Если мне нужно будет поменять тип, мне нужно будет сделать это в одном месте, а не по всему проекту менять строки.
5) как мы обсуждали что нужно убрать из компонентов запросы с бэку. 

Все замечания касаются всего кода относящийся к рефакторинку, в том числе того который ты уже залил. Пробегись по всем файлам которые затронул.

2024-05-26 08:58 UTC, RinVeber commented on frontend/src/components/psy/AssignmentTile.tsx
> +  const [assignmentId, setAssignments] = useState<any>([]);
assingmentTile - это компонент карточки с домашками. В этом пр я не рефачил ее. 
У меня рефакторинг этого компонента в другой ветке и будет залит отдельным пр

2024-05-26 09:03 UTC, RinVeber commented on frontend/src/store/entities/assignments/assingmentsApi.ts
> +          /\s+/g,
Удаляет все пробелы в строке

2024-05-27 06:36 UTC, yuferevaleksey commented on frontend/src/components/psy/AssignmentTile.tsx
> +  const [assignmentId, setAssignments] = useState<any>([]);
Помнишь, мы договаривались что если тронули файл, то по возможности делаем его тоже правильно? Не нужно рефачить весь файл, но вот ПР должне выглядить консистентно, тут мы ТС используем, а тут нет =)

2024-05-27 06:37 UTC, yuferevaleksey commented on frontend/src/store/entities/assignments/assingmentsApi.ts
> +          /\s+/g,
Я имею ввиду напишщи в коде комментарий =)

2024-05-29 14:51 UTC, RinVeber commented on frontend/src/routes/AssignmentsPageRefactor/FilterDropDown/FilterDropDown.tsx
> +      case "add_date": {
На беке в параметр ordering можно закинуть DESC, ASC как по датам, так и по "популярности". Т.е. можно больше 1 параметра закинуть и будет сортировка по ним возвращаться. Тогда по дизайну макета возможно сортировка ТОЛЬКО по дате или популярности. 

Нельзя сортировать одновременно по дате и по популярности. 
На стороне бекенда похоже там какие то трудности с переделкой есть с этим.

На созвоне в среду, хотел это обсудить это подробней

2024-05-30 09:19 UTC, yuferevaleksey commented on frontend/src/store/store.ts
> +    activeTab == "favorites" &&
"favorites" - Нужно избегать использование сравнений со строками. Если таких строк будет много в проекте, при рефакторинге будет слоджно выпилить все, велик шанс пропустить. Хорошей практикой считается константа или enum

2024-05-30 09:19 UTC, yuferevaleksey commented on frontend/src/utils/constants.ts
> +  All = 'all',
Еще раз обращу внимание. Сортировка должна идти по двум полям - одно поле это по чему сортировать второе как сортировать.  DATE_ASC, DATE_DESC, POULAR_ASC, POPULAR_DESC

2024-06-03 10:58 UTC, yuferevaleksey approved these changes

2024-06-04 15:57 UTC, merged