fix: register errors display
InTouch-Val/INtouch pull request #242
Opened 2024-06-02 10:47 UTC by JackSheepe

https://int.kaiten.ru/space/287767/card/33302793?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImNvbXBhcmlzb24iOiJlcSIsImtleSI6Im1lbWJlciIsInZhbHVlIjo1NzAzMTV9XX1dfQ

2024-06-03 06:50 UTC, RinVeber commented on frontend/src/service/forms/regex.jsx
Расширение файла .jsx?

2024-06-04 14:28 UTC, sashadudkina5 commented
@JackSheepe 
Я проверила локально, по валидации все ок
<img width="1440" alt="Screenshot 2024-06-04 at 17 27 35" src="https://github.com/InTouch-Val/INtouch/assets/106837243/ef4973b6-77c5-4100-a3c5-7b0ae3e5c9cf">

Но при нажатии на register вот такая ошибка. Прикладываю скриншот

400 Bad Request


Кажется, стоит при такой ошибке отображать тоже какое нибудь уведомление. А то со стороны юзера кажется , что кнопка просто не работает тк никакого уведомления нет

2024-06-05 16:25 UTC, yuferevaleksey requested changes

2024-06-05 16:25 UTC, yuferevaleksey commented on frontend/src/service/forms/registration-page.tsx
> +  const isAnyFieldMissingOrInvalid = () => {
: boolean

2024-06-05 16:25 UTC, yuferevaleksey commented on frontend/src/service/forms/regex.jsx
> +export const isValidName = (name) => {
export const isValidName = (name): boolean => {

2024-06-11 18:16 UTC, RinVeber commented
Свой аппрув поставил.
Не знаю как другие.
Вроде как договорились, что если начали ревьюить, то каждый должен поставить аппрув?
В итоге тут должно быть 3 аппрува?

2024-06-18 12:30 UTC, yuferevaleksey approved these changes

2024-06-18 13:47 UTC, merged