Refactor  assignment creator
InTouch-Val/INtouch pull request #251
Opened 2024-06-10 15:18 UTC by JackSheepe

Add assignment refactor redux ts

2024-06-10 19:23 UTC, RinVeber commented on frontend/src/components/psy/AddAssignment.tsx
>        const response = await API.get(`assignments/${id}/`);
Запрос на бек должен быть через createThunkFunc который в коробке редакса лежит.

2024-06-10 19:24 UTC, RinVeber commented on frontend/src/components/psy/AddAssignment.tsx
> +      dispatch(setTitle(response.data.title));
Можно всю форму в один объект положить и сделать для него 1 редюсер.

2024-06-10 19:25 UTC, RinVeber commented on frontend/src/components/psy/AddAssignment.tsx
> +    description,
Кажется проще будет положить в 1 объект

2024-06-10 19:30 UTC, RinVeber commented on frontend/src/store/slices/add-assignment/form.ts
> +    setTitle: (state, action: PayloadAction<string>) => {
Предложение.
Половина редюсеров по сути используются для формы. 
Можно сделать редюсер и все нужные данные для формы хранить в одной переменной. Будет по компактней немного.

2024-06-10 19:35 UTC, RinVeber commented on frontend/src/store/actions/add-assignment/index.ts
> +export const addBlock = (
Не совсем понял назначения этих экшенов. 
У тебя же в слайсе есть экшены уже такие? Можно их напрямую диспатчить и редакс сам вернет в промежуточном шаге в стор в виде type и payload.

2024-06-18 10:42 UTC, JackSheepe commented on frontend/src/components/psy/AddAssignment.tsx
> +    description,
Так будет удобнее использовать чем каждый раз прописывать как ключи объекта

2024-06-19 11:58 UTC, RinVeber commented on frontend/src/service/forms/registration-page.tsx
> +        value.length > numberOfMaxLengthOfName
Предложение.

В проекте есть библиотека для работы с формами ```react-hook-forms```. Так же есть библиотека для схем валидацией ```yup```. Не обязательно прописывать все кейсы валидацию в ручную, в библиотеках для этого есть все инструменты.

2024-06-19 12:11 UTC, RinVeber commented on frontend/src/store/slices/add-assignment/blocks.ts
> +        state.blocks[blockIndex] = updatedBlock;
Обычно в редюсер не держат логику с добавлением новых полей по каким либо кейсам. Это делает редюсер не "чистым". Для этого использую функцию ```prepare```.

```
  updateBlock: (
      state,
      action: PayloadAction<UpdateBlockAction["payload"]>
    ) => {
prepare: (block: BlockState) => { 
const updateBlock = [...block]
...
return {payload: updateBlock}
}
reducer: (state, action) => {
state.block.push(action.payload)
}
```

Сначала отработает функция ```prepare```, а после результат измененный результат придет в ```reducer```.
Почитать про это можно здесь https://redux-toolkit.js.org/api/createSlice#customizing-generated-action-creators

Я не знаю насколько это критично, но у нас на курсах ревьюеры к этому придирались))

2024-06-19 12:13 UTC, RinVeber approved these changes

2024-06-19 12:14 UTC, RinVeber commented
Поставил аппрув, конфликты только реши)

2024-06-19 14:03 UTC, yuferevaleksey approved these changes

2024-06-19 14:11 UTC, yuferevaleksey requested changes

2024-06-19 14:11 UTC, yuferevaleksey commented on frontend/src/store/entities/add-assignment/types.ts
> +type reqBlockType = "text" | "open" | "range" | "image" | "single" | "multiple";
Я бы сделал это enum

2024-06-19 14:16 UTC, yuferevaleksey commented on frontend/src/service/forms/registration-page.tsx
> +    field: "email" | "password" | "name" | "second",
enum

2024-06-19 14:19 UTC, JackSheepe commented
А что вы апрувы ставите там, что больше нечего рефачить?

2024-06-26 11:41 UTC, RinVeber approved these changes

2024-06-26 11:42 UTC, RinVeber commented
Отлично! Добавил функцию ```prepare```. Теперь редюсер выглядит по красивей)
Поставил аппрув, только конфликты порешай)

2024-07-01 09:19 UTC, yuferevaleksey approved these changes

2024-07-01 16:58 UTC, merged