Released custom client deleting
InTouch-Val/INtouch pull request #261
Opened 2024-06-12 12:35 UTC by ArtyomKoshurin

Добавил кастомное удаление пользователей и изменил таймзону в настройках, ориентированную на центральное европейское время
Edited: в догонку добавил фикс ласт логина

2024-06-13 18:02 UTC, NechepurenkoA requested changes
В целом все хорошо, пару микро замечаний / исправлений.

2024-06-13 18:02 UTC, NechepurenkoA commented on backend/api/views.py
> +            random.choice(deleted_username) for _ in range(RANDOM_USERNAME_DELETING)
Респект за "_"
Зачем тут random кстати, это какая-то гениальная техника удаления? Или ты какой-то шифр ставишь вместо логина?

2024-06-14 08:30 UTC, ArtyomKoshurin commented on backend/api/views.py
> +            for assignment in Assignment.objects.filter(author=user, is_public=False):
Если задание со статусом черновика - не должны, уже спрашивал

2024-06-14 08:31 UTC, ArtyomKoshurin commented on backend/api/views.py
> +            random.choice(deleted_username) for _ in range(RANDOM_USERNAME_DELETING)
Это тип юзернейм должен быть уникальным, поэтому джанга не дает мне поставить туда deleted, вот и решил сгенерировать рандомную строку, чтобы заглушка была уникальной

2024-06-14 08:33 UTC, ArtyomKoshurin commented on backend/api/constants.py
> +    0: "deleted",
Прикол в том, что True мне для удаления вообще не нужен по сути. Я просто сделал эти константы для вызова по ключам словаря во время удаления. Думал сделать список вместо словаря, но по словарю как то легче ориентироваться, какие значения нужны

2024-06-14 09:47 UTC, NechepurenkoA commented on backend/api/views.py
> +            random.choice(deleted_username) for _ in range(RANDOM_USERNAME_DELETING)
Блин, беда, а что если сгенерит такой, который есть? Ты кстати на пароле тоже это используешь, не слишком опасно?

2024-06-14 09:52 UTC, NechepurenkoA approved these changes
Только комм наверх перекинуть и дев вмержить осталось. Но подумай всё-таки стоит оставлять булы в словаре или нет, спорный момент как по мне.

В остальном супер!

2024-06-14 09:52 UTC, NechepurenkoA commented on backend/api/constants.py
> +# Random default value for username and password on profile's deleting.
Хорошо, только перекинь комм наверх, а то как-то не логично получается)

2024-06-14 10:09 UTC, NechepurenkoA commented on backend/api/views.py
> +        deleted_username = string.ascii_uppercase + string.digits
Перекинь вот это еще в константы, назови как нибудь charset_for_deletion или что-то такое, подумай в общем

2024-06-14 10:19 UTC, merged