Feat/ tumbler componet
InTouch-Val/INtouch pull request #391
Opened 2024-08-29 12:45 UTC by RinVeber

2024-08-31 19:35 UTC, sashadudkina5 commented
Есть предложение, если будет позволять время и загрузка, вынести компонент Тумблер сразу в копмонент Сторибука. Тк скорее всего в будущем так и так нужно будет в сторибук переносить 
@RinVeber

2024-08-31 19:38 UTC, sashadudkina5 commented on frontend/src/components/tumbler/style.module.css
> +@media screen and (min-width: 320px) and (max-width: 480px) {
Если перевести в файл в scss, то тут можно использовать миксин @include mobile()  вместо @media screen and (min-width: 320px) and (max-width: 480px)

2024-09-01 13:05 UTC, RinVeber commented
> Есть предложение, если будет позволять время и загрузка, вынести компонент Тумблер сразу в копмонент Сторибука. Тк скорее всего в будущем так и так нужно будет в сторибук переносить @RinVeber

Да, перенесу туда. Надо бы разобраться как там перенос компонентов в сторибук работает)

2024-09-07 18:34 UTC, DariaBold commented on frontend/src/components/tumbler/style.module.scss
> +  color: #656565;
Необходимо заменить цвета типа #656565 на константы из variables.

2024-09-12 14:38 UTC, RinVeber commented on frontend/src/components/tumbler/style.module.scss
> +  color: #656565;
Поменял цвета в scss)

2024-09-13 14:36 UTC, sashadudkina5 commented
@RinVeber привет!
я посмотрела компонент тумблера в сторибуке 
1. там в папке stories есть небольшая опечатка - tubler
2. сам файл Tumbler.tsx нужно будет перенести тоже в папку tumbler в stories. Там по структуре в папке stories должно выглядеть так:

- папка с названием компонента. В самой папке 3 файла:
Tumbler.tsx
Tumbler.stories.ts
файл со стилями. Сейчас там css файл (кажется, сейчас он никак не используется нигде)

Вижу, что сейчас Tumbler.tsx создан в своей отдельной папке ВНЕ stories. И там же свой отдельный файл style.module.scss. Вот этот scss файл нужно перенести в папку stories/tubler вместо файла css, который там сейчас лежит, а css файл удалить (кажется, сейчас он никак не используется нигде)

2024-09-13 14:39 UTC, sashadudkina5 requested changes

2024-09-13 14:39 UTC, sashadudkina5 commented on frontend/src/stories/tubler/Tumbler.stories.ts
> +import Tumbler from "./Tumbler";
Смотри, ты тут импортируешь файл, которого нет. В другом комменте написала, что нужно перенести Tumbler.tsx в ту же папку

Иначе выдает ошибку + из-за этого в самом сторибуке ошибка
<img width="1440" alt="Screenshot 2024-09-13 at 17 39 31" src="https://github.com/user-attachments/assets/384e9b59-be3a-490d-8d73-3e1a825ecb1a">

2024-09-13 14:40 UTC, sashadudkina5 commented on frontend/src/stories/tubler/Tumbler.stories.ts
> +import Tumbler from "./Tumbler";
![Uploading Screenshot 2024-09-13 at 17.40.40.png…]()

2024-09-17 14:47 UTC, sashadudkina5 commented
@RinVeber 
В Tumbler.tsx нужно удалить импорт "./tumbler.css";, иначе при запуске Сторибука отображается ошибка 
<img width="1440" alt="Screenshot 2024-09-17 at 18 46 56" src="https://github.com/user-attachments/assets/1f514a5e-780f-4984-b5bf-09539f7883ff">

В остальном все хорошо!

2024-09-17 15:01 UTC, RinVeber commented
> @RinVeber В Tumbler.tsx нужно удалить импорт "./tumbler.css";, иначе при запуске Сторибука отображается ошибка <img alt="Screenshot 2024-09-17 at 18 46 56" width="1440" src="https://private-user-images.githubusercontent.com/106837243/368216039-1f514a5e-780f-4984-b5bf-09539f7883ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODU1NTAsIm5iZiI6MTcyNjU4NTI1MCwicGF0aCI6Ii8xMDY4MzcyNDMvMzY4MjE2MDM5LTFmNTE0YTVlLTc4MGYtNDk4NC1iNWJmLTA5NTM5Zjc4ODNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxNTAwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzk2ODRjN2YxMDgyMTU3ZDAyNGYwZjk4ZjNlN2EyYjY0MWU2NTdjOWQ1MWZhOGVkMWI3MGRkMGE5MGEyZTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gow81yKOPHQyWs7Ir23hI3uukBtHmxWSJmOcgeOly8U">
> 
> В остальном все хорошо!

Почему у меня не отображается эта ошибка?(

2024-09-17 15:33 UTC, merged