fix/client-avatar
InTouch-Val/INtouch pull request #409
Opened 2024-09-23 13:32 UTC by DariaBold

Убрала аватар у клиента в сайдбаре, настройках и в списках клиентов, закомментировала неиспользуемую функцию "switchToNotesTab".

2024-09-26 11:59 UTC, sashadudkina5 requested changes

2024-09-26 11:59 UTC, sashadudkina5 commented on frontend/src/components/App.tsx
> +              alt="Something"
Есть предложение в alt написать что-то более содержательное, например "User's photo" иначе смысл alt теряется

2024-09-26 11:59 UTC, sashadudkina5 commented on frontend/src/components/psy/ClientDetailsPage.tsx
> +  // };
Если функция совсем нигде не используется, то можно ее удалить 
Можно через поиск по проекту на всякий случай перепроверить по ключевому слову switchToNotesTab

2024-09-26 11:59 UTC, sashadudkina5 commented on frontend/src/components/psy/ClientDetailsPage.tsx
>                style={{ width: "46px" }}
Если убираем фото, можно не закомментить, а просто удалить элемент

2024-09-26 11:59 UTC, sashadudkina5 commented on frontend/src/routes/SettingPage/settings-page.tsx
> +// import useMobileWidth from "../../utils/hook/useMobileWidth";
тут тоже, Если больше не используем, то лучше удалить совсем строку

То же самое дальше, где закомментирован кусок где используется этот хук

2024-09-26 12:10 UTC, DariaBold commented on frontend/src/components/psy/ClientDetailsPage.tsx
> +  // };
Там просто внизу закомментировано использование этой функции, вот я и саму ее тоже закомментила.

2024-09-29 12:13 UTC, sashadudkina5 approved these changes

2024-10-03 15:48 UTC, merged